---
apiVersion: v1
kind: Service
metadata:
  name: <%= service_name %>
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: <%= service_name %>
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: <%= service_name %>-deployment